export const HINT_NFT = {
    HINT_NFT_ID: "mitum-nft-nft-id-v0.0.1",
    HINT_COLLECTION_POLICY: "mitum-nft-collection-policy-v0.0.1",
    HINT_COLLECITON_REGISTER_FORM: "mitum-nft-collection-register-form-v0.0.1",
    HINT_MINT_FORM: "mitum-nft-mint-form-v0.0.1",
    HINT_NFT_SIGNER: "mitum-nft-signer-v0.0.1",
    HINT_NFT_SIGNERS: "mitum-nft-signers-v0.0.1",
    HINT_COLLECTION_REGISTER_OPERATION_FACT: "mitum-nft-collection-register-operation-fact",
    HINT_COLLECTION_REGISTER_OPERATION: "mitum-nft-collection-register-operation",
    HINT_COLLECTION_POLICY_UPDATER_OPERATION_FACT: "mitum-nft-collection-policy-updater-operation-fact",
    HINT_COLLECTION_POLICY_UPDATER_OPERATION: "mitum-nft-collection-policy-updater-operation",
    HINT_DELEGATE_ITEM: "mitum-nft-delegate-item",
    HINT_DELEGATE_OPERATION_FACT: "mitum-nft-delegate-operation-fact",
    HINT_DELEGATE_OPERATION: "mitum-nft-delegate-operation",
    HINT_APPROVE_ITEM: "mitum-nft-approve-item",
    HINT_APPROVE_OPERATION_FACT: "mitum-nft-approve-operation-fact",
    HINT_APPROVE_OPERATION: "mitum-nft-approve-operation",
    HINT_MINT_ITEM: "mitum-nft-mint-item",
    HINT_MINT_OPERATION_FACT: "mitum-nft-mint-operation-fact",
    HINT_MINT_OPERATION: "mitum-nft-mint-operation",
    HINT_NFT_TRANSFER_ITEM: "mitum-nft-transfer-item",
    HINT_NFT_TRANSFER_OPERATION_FACT: "mitum-nft-transfer-operation-fact",
    HINT_NFT_TRANSFER_OPERATION: "mitum-nft-transfer-operation",
    HINT_NFT_SIGN_ITEM: "mitum-nft-sign-item",
    HINT_NFT_SIGN_OPERATION_FACT: "mitum-nft-sign-operation-fact",
    HINT_NFT_SIGN_OPERATION: "mitum-nft-sign-operation",
};
//# sourceMappingURL=hintNft.js.map