import { Account } from "./account/index.js";
import { Currency } from "./currency/index.js";
import { Block } from "./block/index.js";
import { Operation } from "./operation/index.js";
import { AxiosResponse } from "axios";
import { Contract } from "./contract/index.js";
import { Nft } from "./contract/nft/index.js";
import { Credential } from "./contract/credential/index.js";
import { Timestamp } from "./contract/timestamp/index.js";
import { St } from "./contract/st/index.js";
import { Kyc } from "./contract/kyc/index.js";
import { Dao } from "./contract/dao/index.js";
export declare class Mitum {
    private _version;
    private _node;
    private _chain;
    account: Account;
    currency: Currency;
    block: Block;
    operation: Operation;
    contract: Contract;
    nft: Nft;
    credential: Credential;
    timestamp: Timestamp;
    st: St;
    kyc: Kyc;
    dao: Dao;
    constructor(provider?: string);
    version(): string;
    node(): Promise<AxiosResponse>;
    setNode(provider?: string): void;
    getNode(): string;
    chain(): string;
    setChain(networkID: string): void;
}
export default Mitum;
