"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SUFFIX = exports.HINT = void 0;
exports.HINT = {
    FACT_SIGN: "base-fact-sign",
    KEY: "mitum-currency-key",
    KEYS: "mitum-currency-keys",
    ETH_KEYS: "mitum-currency-eth-keys",
    AMOUNT: "mitum-currency-amount",
    CREATE_ACCOUNTS_ITEM: "mitum-currency-create-account-multiple-amounts",
    CREATE_ACCOUNTS_OPERATION_FACT: "mitum-currency-create-account-operation-fact",
    CREATE_ACCOUNTS_OPERATION: "mitum-currency-create-account-operation",
    KEY_UPDATER_OPERATION_FACT: "mitum-currency-update-key-operation-fact",
    KEY_UPDATER_OPERATION: "mitum-currency-update-key-operation",
    TRANSFERS_ITEM: "mitum-currency-transfer-item-multi-amounts",
    TRANSFERS_OPERATION_FACT: "mitum-currency-transfer-operation-fact",
    TRANSFERS_OPERATION: "mitum-currency-transfer-operation",
    CURRENCY_REGISTER_OPERATION_FACT: "mitum-currency-register-currency-operation-fact",
    CURRENCY_REGISTER_OPERATION: "mitum-currency-register-currency-operation",
    CURRENCY_POLICY_UPDATER_OPERATION_FACT: "mitum-currency-update-currency-operation-fact",
    CURRENCY_POLICY_UPDATER_OPERATION: "mitum-currency-update-currency-operation",
    SUFFRAGE_INFLATION_ITEM: "mitum-currency-mint-item",
    SUFFRAGE_INFLATION_OPERATION_FACT: "mitum-currency-mint-operation-fact",
    SUFFRAGE_INFLATION_OPERATION: "mitum-currency-mint-operation",
    CURRENCY_DESIGN: "mitum-currency-currency-design",
    CURRENCY_POLICY: "mitum-currency-currency-policy",
    CURRENCY_FEEER_NIL: "mitum-currency-nil-feeer",
    CURRENCY_FEEER_FIXED: "mitum-currency-fixed-feeer",
    CURRENCY_FEEER_RATIO: "mitum-currency-ratio-feeer",
    CREATE_CONTRACT_ACCOUNTS_ITEM: "mitum-currency-create-contract-account-multiple-amounts",
    CREATE_CONTRACT_ACCOUNTS_OPERATION_FACT: "mitum-currency-create-contract-account-operation-fact",
    CREATE_CONTRACT_ACCOUNTS_OPERATION: "mitum-currency-create-contract-account-operation",
    WITHDRAWS_ITEM: "mitum-currency-contract-account-withdraw-item-multi-amounts",
    WITHDRAWS_ITEM_SIN_AMOUNT: "mitum-currency-contract-account-withdraw-item-single-amount",
    UPDATE_OPERATOR_OPERATION_FACT: "mitum-currency-contract-account-update-operator-operation-fact",
    UPDATE_OPERATOR_OPERATION: "mitum-currency-contract-account-update-operator-operation",
    WITHDRAWS_OPERATION_FACT: "mitum-currency-contract-account-withdraw-operation-fact",
    WITHDRAWS_OPERATION: "mitum-currency-contract-account-withdraw-operation",
};
exports.SUFFIX = {
    KEY_PRIVATE: "mpr",
    KEY_PUBLIC: "mpu",
    ACCOUNT_ADDRESS: "mca",
    KEY_ETHER_PRIVATE: "epr",
    KEY_ETHER_PUBLIC: "epu",
    ETHER_ACCOUNT_ADDRESS: "eca",
    NODE_ADDRESS: "sas",
    ZERO_ADDRESS: "-Xmca",
};
//# sourceMappingURL=hint.js.map