import { AxiosResponse } from "axios";
import { Creator } from "./creatorType.js";
import { OperationType } from "../../types/operation.js";
import { Fact } from "../../types/fact.js";
export declare class Nft {
    private _networkID;
    private _node;
    private _address;
    private _collection;
    constructor(networkID: string, provider?: string);
    private _setNode;
    private _setChain;
    setGallery(contractAddress: string, collectionID: string): void;
    setCollection(collectionID: string): void;
    getContractAddress(): string;
    getCollectionId(): string;
    ownerOf(tokenID: number): Promise<AxiosResponse>;
    name(): void;
    symbol(): string;
    tokenURI(): void;
    private gererateCreator;
    mint(sender: string, uri: string, hash: string, currencyID: string, creator: string): OperationType<Fact>;
    mintForMultiCreators(sender: string, uri: string, hash: string, currencyID: string, creator: Creator[]): OperationType<Fact>;
    safeTransferFrom(): void;
    transferFrom(): void;
    approve(): void;
    getApproved(): void;
    setApprovalForAll(): void;
    isApprovedForAll(): void;
}
